### ISSUE TITLE
_BaseValue error

### ISSUE THREAD

**Issue by taburaad** [uchicago-cloud/mpcs51033-2017-spring-forum#18]
Hi,

When I try to iterate through a list of keys like this: [Key('Photo', 6173208034148352)]

App Engine returns each element like this: _BaseValue(Key('Photo', 6173208034148352))

Does anyone know how to prevent this or cast out of '_BaseValue' and back into a Key?

Thanks

**Comment by tabinks** [comment]
I think the problem is you that the argument you're passing is not correct.  Look at this:
* http://stackoverflow.com/questions/1117104/in-google-app-engine-what-is-the-difference-between-model-getkey-and-model-ge
* And the docs: https://cloud.google.com/appengine/docs/standard/python/datastore/entities?csw=1#Paths_and_Key_Uniqueness

**Comment by taburaad** [comment]
Thanks, this ended up working well: list_of_entities = ndb.get_multi(list_of_keys)

From
https://cloud.google.com/appengine/docs/standard/python/ndb/creating-entities
